import { LayoutDataSource } from '@n7-frontend/core/dist/layout-data-source';
import { Observable } from 'rxjs';
export declare class AwSearchLayoutDS extends LayoutDataSource {
    private destroyed$;
    private communication;
    private configuration;
    private mainState;
    private search;
    private searchModel;
    private prettifyLabels;
    private configKeys;
    private fallback;
    private resetButtonEnabled;
    pageTitle: string;
    resultsTitle: string;
    totalCount: number;
    currentPage: any;
    pageSize: number;
    sidebarIsSticky: boolean;
    isFirstLoading: boolean;
    resultsLoading: boolean;
    orderBy: string;
    orderDirection: string;
    options: any;
    orderByLabel: string;
    orderByOptions: any;
    onInit({ configuration, mainState, options, communication, search, }: {
        configuration: any;
        mainState: any;
        options: any;
        communication: any;
        search: any;
    }): void;
    onDestroy(): void;
    onSearchResponse(): void;
    onOrderByChange(payload: any): void;
    onPageSizeChange(size: any): Observable<boolean>;
    onPaginationChange(payload: any): Observable<boolean>;
    onPaginationGoToChange(payload: any): Observable<boolean>;
    drawPagination: () => void;
    resetPagination(): void;
    onResultsLimitChange(payload: any): void;
    setLimit(payload: any): void;
    getSearchModelId: () => string;
    doSearchRequest$(): Observable<any>;
    private _updateSearchPage;
    private _addFacetsLabels;
    private _addFacetsOptions;
    private _normalizeItems;
    private _sidebarStickyControl;
    private _getPaginationParams;
}
