import { ActivatedRoute, Router } from '@angular/router';
import { Subject } from 'rxjs';
import { CommunicationService } from '../../common/services/communication.service';
export declare const INPUT_STATE_CONTEXT = "input";
export declare const FACET_STATE_CONTEXT = "facet";
export declare const RESULTS_STATE_CONTEXT = "results";
export declare const LINKS_STATE_CONTEXT = "links";
export declare class MrSearchService {
    private router;
    private activatedRoute;
    private communication;
    private config;
    private queryParamKeys;
    private contextState;
    private state$;
    private beforeHook;
    constructor(router: Router, activatedRoute: ActivatedRoute, communication: CommunicationService);
    init(config: any): void;
    getConfig: () => any;
    getState$(context: string, id?: string): Subject<any>;
    addStateContext(context: string): void;
    addState(context: string, id: string): void;
    setState(context: string, id: string, newValue: any): void;
    setBeforeHook(context: string, id: string, hook: any): void;
    reset(): void;
    private setContextState;
    private initInputState;
    private initFacetState;
    private onRouteChange;
    private onInputsChange;
    private onResultsLoading;
}
